title: Civic AI in Town
description: initial documentation 
author: AlekSasha
email: aleksasha@example.com

remote_theme: just-the-docs/just-the-docs

repository: ""
url: "https://aleksasha88.github.io"          
baseurl: "/civicai-in-town"       

nav_order:
  - index.md
  - getting-started.md
  - page1.md

exclude:
  - README.md       # Keep the GitHub readme from becoming a webpage
  - draft_notes/    # Ignore an entire folder of rough drafts

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
